import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';

import 'models/transaction_model.dart';
import 'providers/transaction_provider.dart';
import 'screens/home_screen.dart';
import 'services/hive_service.dart';

// main() is the first function Flutter runs.
// It is async because Hive needs time to initialize before the UI starts.
Future<void> main() async {
  // Makes sure Flutter is ready before we call async setup code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initializes Hive storage for Flutter.
  // On Android/iOS, Hive stores data on the device.
  // On web/Chrome, Hive stores data in the browser storage for the current localhost port.
  await Hive.initFlutter();

  // Registers the enum adapter generated by build_runner.
  // The typeId 0 must match @HiveType(typeId: 0) in transaction_model.dart.
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(TransactionTypeAdapter());
  }

  // Registers the model adapter generated by build_runner.
  // The typeId 1 must match @HiveType(typeId: 1) in transaction_model.dart.
  if (!Hive.isAdapterRegistered(1)) {
    Hive.registerAdapter(TransactionModelAdapter());
  }

  // Creates the service that opens and talks to the Hive box.
  final hiveService = HiveService();

  // Opens the transactions box before Provider tries to read saved data.
  await hiveService.openTransactionBox();

  // Starts the app and makes TransactionProvider available to all child screens.
  runApp(
    ChangeNotifierProvider(
      // Creates the provider, gives it HiveService, then immediately loads saved data.
      create: (context) => TransactionProvider(hiveService: hiveService)
        ..loadTransactions(),

      // MyApp is the root widget of the app.
      child: const MyApp(),
    ),
  );
}

// MyApp contains app-wide setup like theme and first screen.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Removes the red debug banner from the top-right corner.
      debugShowCheckedModeBanner: false,

      // App name used by Flutter.
      title: 'Money Buddy',

      // Basic app theme.
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
        useMaterial3: true,
      ),

      // This is the first screen shown when the app opens.
      home: const HomeScreen(),
    );
  }
}
